---

debian_packages:
  - apt-transport-https 
  - ca-certificates 
  - curl 
  - gnupg2 
  - software-properties-common 
  - jq 
  - git 
  - default-jre
hostname: lsio-build-slave
jenkins_default_user: jenkins
manage_keys: False