---

- name: install multi arch systemd service
  copy:
    src: etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify:
    - restart docker
    - start and enable multiarch service

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/home/{{ jenkins_default_user }}/.docker/config.json"
    line: "echo '{\"experimental\": \"enabled\"}'"