---
- name: ensure all packages are up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: install packages listed
  apt: 
    name: "{{ item }}" 
    state: present
  with_items: "{{ debian_packages }}"

- name: set hostname for slave
  hostname:
    name: "{{ hostname }}"