---

- name: user setup
  include: user-setup.yml

- name: initial slave setup
  include: initial-setup.yml

- name: docker multiarch setup
  include: docker-multiarch.yml

# only runs when defaults manage_keys is set to true
- name: ssh-keys
  include: ssh-keys.yml
  when: manage_keys